theme: jekyll-theme-cayman

title: India With Migrants
description: "COVID-19 and associated lockdown in India has created a migrant labourer crisis 
where millions of poor Indian migran labours are stuck in cities without any food, income, or 
support. During this time, 
common Indians from all walks of life have come up for the help of these labourers. This 
website is to collect their efforts, in a public record.
If you would want to help fund their efforts, please contact them with the link given in the 
table below."
image: https://raw.githubusercontent.com/Sheikh-Aman/IndiaWithMigrants/master/assets/img/social_preview.png

show_downloads: false
google_analytics: UA-167217482-1

defaults:
  - scope:
      path: ""
    values:
      image: https://raw.githubusercontent.com/Sheikh-Aman/IndiaWithMigrants/master/assets/img/social_preview.png

twitter:
  username: AmanAlam